name: Master Workflow
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        env:
          LogLevel: DEBUG
        with:
          arguments: build
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          profile: default
      - name: Run deploy
        env:
          LogLevel: DEBUG
        run: deploy/dv/deploy-dv.sh
